create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.productos(id) on delete set null,
  producto text,
  tipo text not null,
  cantidad numeric not null default 0,
  stock_anterior numeric not null default 0,
  stock_nuevo numeric not null default 0,
  referencia_tipo text,
  referencia_id bigint,
  nota text,
  fecha_movimiento timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.reclamaciones_garantia (
  id bigint generated by default as identity primary key,
  garantia_id bigint references public.garantias(id) on delete cascade,
  motivo text not null,
  diagnostico text,
  resolucion text,
  estado text not null default 'En revisión',
  notas text,
  fecha_reclamacion timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.ordenes_compra_detalle add column if not exists producto_id bigint references public.productos(id) on delete set null;
alter table public.ordenes_compra add column if not exists fecha_recepcion timestamptz;
alter table public.movimientos_caja add column if not exists fecha_movimiento timestamptz default now();

create index if not exists idx_mov_inv_producto on public.movimientos_inventario(producto_id);
create index if not exists idx_mov_inv_referencia on public.movimientos_inventario(referencia_tipo, referencia_id);
create index if not exists idx_reclamos_garantia on public.reclamaciones_garantia(garantia_id);
