-- TECHSOUL OS — Agenda + Corte de Caja
-- Ejecutar en Supabase > SQL Editor > New Query

alter table public.ordenes
  add column if not exists fecha_programada timestamptz,
  add column if not exists duracion_estimada_min integer;

create table if not exists public.citas_agenda (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id) on delete set null,
  orden_id bigint references public.ordenes(id) on delete set null,
  nombre_cliente varchar(180) not null,
  telefono varchar(50),
  equipo varchar(180),
  servicio varchar(220) not null,
  inicio timestamptz not null,
  duracion_min integer not null default 30 check (duracion_min > 0),
  estado varchar(60) not null default 'Cita',
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cortes_caja (
  id bigint generated by default as identity primary key,
  fecha date not null unique,
  efectivo_entradas numeric(12,2) not null default 0,
  efectivo_salidas numeric(12,2) not null default 0,
  efectivo_esperado numeric(12,2) not null default 0,
  efectivo_contado numeric(12,2) not null default 0,
  diferencia numeric(12,2) not null default 0,
  transferencia_entradas numeric(12,2) not null default 0,
  transferencia_salidas numeric(12,2) not null default 0,
  tarjeta_entradas numeric(12,2) not null default 0,
  tarjeta_salidas numeric(12,2) not null default 0,
  tarjeta_comision_estimada numeric(12,2) not null default 0,
  total_cobrado numeric(12,2) not null default 0,
  observaciones text,
  detalle jsonb not null default '{}'::jsonb,
  cerrado_por uuid,
  cerrado_en timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_citas_agenda_inicio on public.citas_agenda(inicio);
create index if not exists idx_citas_agenda_orden on public.citas_agenda(orden_id);
create index if not exists idx_ordenes_fecha_programada on public.ordenes(fecha_programada);
create index if not exists idx_cortes_caja_fecha on public.cortes_caja(fecha);

alter table public.citas_agenda enable row level security;
alter table public.cortes_caja enable row level security;

drop policy if exists "Permitir todo citas agenda" on public.citas_agenda;
create policy "Permitir todo citas agenda"
on public.citas_agenda for all using (true) with check (true);

drop policy if exists "Permitir todo cortes caja" on public.cortes_caja;
create policy "Permitir todo cortes caja"
on public.cortes_caja for all using (true) with check (true);
