-- TechSoul OS · Ventas inteligentes
-- Ejecutar en Supabase SQL Editor antes de usar el módulo con backend remoto.

alter table if exists public.ventas
  add column if not exists folio text,
  add column if not exists cliente_nombre text default 'Cliente de mostrador',
  add column if not exists cliente_telefono text,
  add column if not exists anticipo numeric(12,2) default 0,
  add column if not exists pagado numeric(12,2) default 0,
  add column if not exists saldo numeric(12,2) default 0,
  add column if not exists estado_pago text default 'Pagado',
  add column if not exists estado_entrega text default 'Entregado',
  add column if not exists fecha_venta timestamptz default now();

alter table if exists public.detalle_ventas
  alter column producto_id drop not null;

alter table if exists public.detalle_ventas
  add column if not exists tipo_item text default 'inventario',
  add column if not exists descripcion text,
  add column if not exists subtotal numeric(12,2) default 0,
  add column if not exists costo_estimado numeric(12,2) default 0,
  add column if not exists proveedor text,
  add column if not exists fecha_estimada date,
  add column if not exists estado_entrega text default 'entregado',
  add column if not exists notas text;

create table if not exists public.solicitudes_compra (
  id bigint generated by default as identity primary key,
  venta_id bigint references public.ventas(id) on delete cascade,
  detalle_venta_id bigint references public.detalle_ventas(id) on delete set null,
  descripcion text not null,
  cantidad numeric(12,2) not null default 1,
  costo_estimado numeric(12,2) default 0,
  proveedor text,
  fecha_estimada date,
  estado text not null default 'Pendiente',
  cliente_nombre text,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists idx_detalle_ventas_venta_id on public.detalle_ventas(venta_id);
create index if not exists idx_detalle_ventas_estado on public.detalle_ventas(estado_entrega);
create index if not exists idx_solicitudes_compra_estado on public.solicitudes_compra(estado);
create index if not exists idx_solicitudes_compra_venta_id on public.solicitudes_compra(venta_id);
