-- TechSoul OS · Firma remota de garantía por WhatsApp
-- Ejecutar UNA VEZ en Supabase > SQL Editor.

create table if not exists public.garantia_firmas_remotas (
  id bigint generated by default as identity primary key,
  garantia_id bigint not null references public.garantias(id) on delete cascade,
  orden_id bigint references public.ordenes(id) on delete set null,
  token uuid not null unique,
  folio_garantia text not null,
  fecha_emision timestamptz not null default now(),
  cliente_nombre text,
  cliente_telefono text,
  equipo text,
  serie text,
  servicio text not null,
  dias_garantia integer not null default 0,
  condiciones text,
  firmante_nombre text,
  firmante_correo text,
  firmante_telefono text,
  firma_data_url text,
  acepto_condiciones boolean not null default false,
  firmado_en timestamptz,
  creado_en timestamptz not null default now()
);
create index if not exists garantia_firmas_remotas_token_idx on public.garantia_firmas_remotas(token);
create index if not exists garantia_firmas_remotas_garantia_idx on public.garantia_firmas_remotas(garantia_id);
alter table public.garantia_firmas_remotas enable row level security;

-- El navegador público NO obtiene acceso directo a la tabla.
revoke all on public.garantia_firmas_remotas from anon;
grant select, insert on public.garantia_firmas_remotas to authenticated;

drop policy if exists "staff read remote warranty signatures" on public.garantia_firmas_remotas;
create policy "staff read remote warranty signatures" on public.garantia_firmas_remotas for select to authenticated using (true);
drop policy if exists "staff create remote warranty signatures" on public.garantia_firmas_remotas;
create policy "staff create remote warranty signatures" on public.garantia_firmas_remotas for insert to authenticated with check (true);

-- RPC pública: solo devuelve la garantía correspondiente al token UUID presentado.
create or replace function public.obtener_garantia_para_firma(p_token uuid)
returns setof public.garantia_firmas_remotas
language sql security definer set search_path = public
as $$ select * from public.garantia_firmas_remotas where token = p_token limit 1; $$;

-- RPC pública: permite firmar una sola vez y no permite alterar los datos de la garantía.
create or replace function public.firmar_garantia_remota(
  p_token uuid, p_nombre text, p_correo text, p_telefono text, p_firma_data_url text
) returns boolean
language plpgsql security definer set search_path = public
as $$
begin
  update public.garantia_firmas_remotas
  set firmante_nombre = nullif(trim(p_nombre), ''),
      firmante_correo = nullif(trim(coalesce(p_correo,'')), ''),
      firmante_telefono = nullif(trim(coalesce(p_telefono,'')), ''),
      firma_data_url = p_firma_data_url,
      acepto_condiciones = true,
      firmado_en = now()
  where token = p_token and firmado_en is null
    and nullif(trim(p_nombre), '') is not null
    and p_firma_data_url like 'data:image/png;base64,%';
  return found;
end; $$;

revoke all on function public.obtener_garantia_para_firma(uuid) from public;
revoke all on function public.firmar_garantia_remota(uuid,text,text,text,text) from public;
grant execute on function public.obtener_garantia_para_firma(uuid) to anon, authenticated;
grant execute on function public.firmar_garantia_remota(uuid,text,text,text,text) to anon, authenticated;
