<script setup>
import { onMounted,ref,computed } from 'vue'
import { knowledgeRepository } from '../repositories/knowledge.repository'
import { aiRepository } from '../repositories/ai.repository'
const tab=ref('faq'),items=ref([]),loading=ref(false),error=ref(''),busqueda=ref(''),resultados=ref([])
const tipos={faq:{titulo:'Preguntas frecuentes',campos:['pregunta','respuesta','categoria']},promociones:{titulo:'Promociones',campos:['nombre','descripcion']},plantillas:{titulo:'Plantillas de respuesta',campos:['nombre','contenido','categoria']}}
const nuevo=ref({})
function reset(){nuevo.value=tab.value==='faq'?{pregunta:'',respuesta:'',categoria:'General',palabras_clave:[],prioridad:0,activo:true}:tab.value==='promociones'?{nombre:'',descripcion:'',condiciones:'',fecha_inicio:null,fecha_fin:null,activo:true}:{nombre:'',contenido:'',categoria:'General',palabras_clave:[],activo:true}}
async function cargar(){loading.value=true;error.value='';try{items.value=await knowledgeRepository.list(tab.value)}catch(e){error.value=e.message}finally{loading.value=false}}
async function cambiar(t){tab.value=t;reset();await cargar()}
function keywordsToText(v){return Array.isArray(v)?v.join(', '):''}
function setKeywords(obj,e){obj.palabras_clave=e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}
async function crear(){try{await knowledgeRepository.create(tab.value,nuevo.value);reset();await cargar()}catch(e){error.value=e.message}}
async function guardar(i){try{await knowledgeRepository.update(tab.value,i.id,i)}catch(e){error.value=e.message}}
async function eliminar(i){if(!confirm('¿Eliminar este registro?'))return;try{await knowledgeRepository.remove(tab.value,i.id);await cargar()}catch(e){error.value=e.message}}
async function probarBusqueda(){try{resultados.value=await aiRepository.buscar(busqueda.value)}catch(e){error.value=e.message}}
const titulo=computed(()=>tipos[tab.value].titulo)
onMounted(()=>{reset();cargar()})
</script>
<template><section class="ts-module-page"><header class="ts-module-header"><div><span class="ts-eyebrow">Preparación para IA</span><h2>Base de conocimiento</h2><p>Información editable que utilizará el agente para cotizar y responder mensajes.</p></div></header>
<div class="knowledge-tabs"><button v-for="(v,k) in tipos" :key="k" :class="{active:tab===k}" @click="cambiar(k)">{{v.titulo}}</button></div><div v-if="error" class="alert alert-danger">{{error}}</div>
<div class="knowledge-layout"><div><div class="ts-panel p-4 mb-3"><h3>Nuevo registro</h3><template v-if="tab==='faq'"><input v-model="nuevo.pregunta" class="form-control mb-2" placeholder="Pregunta"><textarea v-model="nuevo.respuesta" class="form-control mb-2" rows="4" placeholder="Respuesta"></textarea><input v-model="nuevo.categoria" class="form-control mb-2" placeholder="Categoría"></template><template v-else-if="tab==='promociones'"><input v-model="nuevo.nombre" class="form-control mb-2" placeholder="Nombre"><textarea v-model="nuevo.descripcion" class="form-control mb-2" placeholder="Descripción"></textarea><textarea v-model="nuevo.condiciones" class="form-control mb-2" placeholder="Condiciones"></textarea><div class="row g-2"><div class="col"><input v-model="nuevo.fecha_inicio" type="date" class="form-control"></div><div class="col"><input v-model="nuevo.fecha_fin" type="date" class="form-control"></div></div></template><template v-else><input v-model="nuevo.nombre" class="form-control mb-2" placeholder="Nombre"><textarea v-model="nuevo.contenido" class="form-control mb-2" rows="5" placeholder="Respuesta modelo"></textarea><input v-model="nuevo.categoria" class="form-control mb-2" placeholder="Categoría"></template><input v-if="tab!=='promociones'" :value="keywordsToText(nuevo.palabras_clave)" @input="setKeywords(nuevo,$event)" class="form-control mt-2" placeholder="Palabras clave separadas por coma"><button class="btn btn-primary mt-3" @click="crear">Agregar</button></div>
<div class="ts-panel p-4"><h3>{{titulo}}</h3><p v-if="loading">Cargando…</p><article v-for="i in items" :key="i.id" class="knowledge-item"><div class="d-flex justify-content-between gap-2"><strong>{{i.pregunta||i.nombre}}</strong><label><input v-model="i.activo" type="checkbox"> Activo</label></div><textarea v-model="i.respuesta" v-if="tab==='faq'" class="form-control mt-2" rows="3"></textarea><textarea v-model="i.descripcion" v-else-if="tab==='promociones'" class="form-control mt-2" rows="3"></textarea><textarea v-model="i.contenido" v-else class="form-control mt-2" rows="3"></textarea><div class="mt-2 d-flex gap-2"><button class="btn btn-outline-primary btn-sm" @click="guardar(i)">Guardar</button><button class="btn btn-outline-danger btn-sm" @click="eliminar(i)">Eliminar</button></div></article></div></div>
<aside class="ts-panel p-4"><h3>Prueba del buscador IA</h3><p class="text-muted">Escribe como lo haría un cliente.</p><div class="input-group"><input v-model="busqueda" class="form-control" placeholder="Ej. pantalla verde 14 pro" @keyup.enter="probarBusqueda"><button class="btn btn-primary" @click="probarBusqueda">Buscar</button></div><article v-for="r in resultados" :key="r.tipo+r.referencia_id" class="search-result"><small>{{r.tipo}} · {{r.categoria}}</small><strong>{{r.titulo}}</strong><p>{{r.contenido}}</p></article></aside></div></section></template>
<style scoped>.knowledge-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.knowledge-tabs button{border:1px solid #dbe3f1;background:#fff;padding:10px 14px;border-radius:10px;font-weight:700}.knowledge-tabs .active{background:#2563eb;color:#fff}.knowledge-layout{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:18px}.knowledge-item,.search-result{padding:16px 0;border-bottom:1px solid #e7edf7}.search-result strong,.search-result small{display:block}.search-result p{white-space:pre-line;margin:6px 0 0}@media(max-width:1000px){.knowledge-layout{grid-template-columns:1fr}}</style>
