<script setup>
import { onMounted, reactive, ref } from 'vue'
import { agentRepository } from '../repositories/agent.repository'
const saving=ref(false), notice=ref(''), error=ref('')
const form=reactive({nombre:'Soul',tono:'amable_profesional',saludo:'¡Hola! Soy Soul, asistente virtual de TechSoul. ¿En qué equipo te ayudo?',despedida:'Con gusto te esperamos en TechSoul.',instrucciones:'No inventes precios, disponibilidad, diagnósticos, garantías ni tiempos.',activo:true,reglas:{no_inventar_precios:true,no_confirmar_stock_sin_consulta:true,escalar_humedad:true,escalar_placa:true,escalar_cuentas:true}})
onMounted(async()=>{try{const data=await agentRepository.getConfig();if(data)Object.assign(form,data,{reglas:{...form.reglas,...(data.reglas||{})}})}catch(e){error.value=e.message}})
async function save(){saving.value=true;notice.value='';error.value='';try{await agentRepository.saveConfig({...form,reglas:{...form.reglas}});notice.value='Configuración del agente guardada.'}catch(e){error.value=e.message}finally{saving.value=false}}
</script>
<template><section class="page"><header><div><span>TechSoul AI · Fase 1</span><h2>Perfil y reglas del agente</h2><p>Define cómo atenderá antes de conectarlo a WhatsApp.</p></div><button @click="save" :disabled="saving">{{saving?'Guardando…':'Guardar cambios'}}</button></header><div v-if="error" class="alert error">{{error}}</div><div v-if="notice" class="alert ok">{{notice}}</div><div class="grid"><article class="panel"><h3>Identidad</h3><label>Nombre<input v-model="form.nombre"></label><label>Tono<select v-model="form.tono"><option value="amable_profesional">Amable y profesional</option><option value="cercano">Cercano</option><option value="directo">Directo</option></select></label><label>Saludo<textarea v-model="form.saludo" rows="4"></textarea></label><label>Despedida<textarea v-model="form.despedida" rows="3"></textarea></label><label>Instrucciones generales<textarea v-model="form.instrucciones" rows="6"></textarea></label><label class="toggle"><input v-model="form.activo" type="checkbox"> Agente activo</label></article><article class="panel"><h3>Reglas de seguridad</h3><label class="rule"><input v-model="form.reglas.no_inventar_precios" type="checkbox"><div><strong>No inventar precios</strong><small>Solo usa importes registrados en el catálogo.</small></div></label><label class="rule"><input v-model="form.reglas.no_confirmar_stock_sin_consulta" type="checkbox"><div><strong>No asegurar disponibilidad</strong><small>Consulta existencias antes de confirmar.</small></div></label><label class="rule"><input v-model="form.reglas.escalar_humedad" type="checkbox"><div><strong>Escalar equipos mojados</strong><small>Da primeros auxilios y solicita revisión técnica.</small></div></label><label class="rule"><input v-model="form.reglas.escalar_placa" type="checkbox"><div><strong>Escalar fallas de placa</strong><small>No promete reparación sin diagnóstico.</small></div></label><label class="rule"><input v-model="form.reglas.escalar_cuentas" type="checkbox"><div><strong>Escalar cuentas y liberaciones</strong><small>Solicita propiedad y revisión humana.</small></div></label></article></div></section></template>
<style scoped>.page{max-width:1200px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;align-items:start;gap:18px;margin-bottom:20px}header span{font-size:11px;font-weight:800;color:#2563eb;text-transform:uppercase;letter-spacing:.12em}h2{margin:5px 0;color:#101828}header p{margin:0;color:#667085}header button{border:0;background:#2563eb;color:white;border-radius:10px;padding:11px 16px;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.panel{background:white;border:1px solid #e4e7ec;border-radius:16px;padding:22px}.panel h3{margin-top:0}.panel>label:not(.rule):not(.toggle){display:grid;gap:7px;margin-bottom:15px;color:#344054;font-size:13px;font-weight:700}input,select,textarea{border:1px solid #d0d5dd;border-radius:10px;padding:11px;font:inherit}.rule{display:flex;gap:12px;padding:15px 0;border-bottom:1px solid #eaecf0}.rule input{width:18px;height:18px}.rule strong,.rule small{display:block}.rule small{color:#667085;margin-top:4px}.toggle{display:flex;gap:9px;align-items:center}.alert{padding:12px;border-radius:10px;margin-bottom:14px}.error{background:#fef3f2;color:#b42318}.ok{background:#ecfdf3;color:#027a48}@media(max-width:800px){.grid{grid-template-columns:1fr}.page{padding:18px 14px}header{flex-direction:column}}</style>
