<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { calculateQuote, getPricingSettings, savePricingSettings, getQuotes, saveQuotes, getRates, saveRates, money } from '../lib/pricing'
const router=useRouter(); const settings=ref(getPricingSettings()); const quotes=ref(getQuotes()); const form=ref({marca:'Samsung',modelo:'',servicio:'Pantalla',calidad:'',costo_pieza:0,envio:0,riesgo:'medio',cliente:'',precio_final:0}); const showSettings=ref(false)
const result=computed(()=>calculateQuote(form.value,settings.value)); const finalPrice=computed(()=>Number(form.value.precio_final||result.value.recommended)); const finalMargin=computed(()=>finalPrice.value?((finalPrice.value-result.value.realCost)/finalPrice.value)*100:0)
function saveSettings(){ savePricingSettings(settings.value); alert('Configuración guardada') }
function saveQuote(){ if(!form.value.modelo||!form.value.costo_pieza) return alert('Captura modelo y costo de pieza'); const q={...form.value,...result.value,precio_final:finalPrice.value,margen_final:finalMargin.value,id:crypto.randomUUID(),creado_en:new Date().toISOString()}; quotes.value=saveQuotes([q,...quotes.value]); alert('Cotización guardada') }

function addInventoryPart(){
  if(!form.value.modelo || !form.value.costo_pieza) return alert('Captura modelo y costo de pieza')
  const nombre=[form.value.servicio, form.value.marca, form.value.modelo, form.value.calidad].filter(Boolean).join(' ')
  localStorage.setItem('techsoul_inventory_draft_v1', JSON.stringify({
    nombre, categoria:'Refacciones', tipo_producto:form.value.servicio || 'Otra', marca:form.value.marca,
    compatible_con:form.value.modelo, calidad:form.value.calidad, modalidad:'bajo_pedido',
    costo:Number(form.value.costo_pieza||0)+Number(form.value.envio||0), precio_venta:finalPrice.value,
    stock:0, stock_minimo:0, proveedor:'', ubicacion:'', notas:'Creada desde el cotizador inteligente'
  }))
  router.push('/inventario')
}
function addRate(){ const rates=getRates(); rates.unshift({id:crypto.randomUUID(),marca:form.value.marca,modelo:form.value.modelo,servicio:form.value.servicio,calidad:form.value.calidad,precio_publico:finalPrice.value,precio_minimo:result.value.minimum,costo_actual:Number(form.value.costo_pieza),activo:true,origen:'Cotizador',actualizado_en:new Date().toISOString()}); saveRates(rates); alert('Precio agregado al tarifario') }
</script>
<template><section class="ts-module-page"><header class="ts-module-header"><div><span class="ts-eyebrow">Reparaciones especiales</span><h2>Cotizador inteligente</h2><p>Para Android, tablets o trabajos que todavía no tienen precio establecido.</p></div><button class="ts-action-secondary" @click="showSettings=!showSettings">{{showSettings?'Ocultar':'Configurar cálculo'}}</button></header>
<article v-if="showSettings" class="ts-panel ts-form-panel"><div class="ts-panel-heading"><div><span class="ts-panel-kicker">Reglas del negocio</span><h3>Cálculo rentable y estable</h3></div><button class="ts-action-primary" @click="saveSettings">Guardar configuración</button></div><div class="ts-smart-form"><label class="ts-field"><span>Operación por reparación</span><input v-model.number="settings.costo_operativo_inicial" type="number"></label><label class="ts-field"><span>Margen mínimo %</span><input v-model.number="settings.margen_minimo" type="number"></label><label class="ts-field"><span>Margen recomendado %</span><input v-model.number="settings.margen_recomendado" type="number"></label><label class="ts-field"><span>Reserva de garantía %</span><input v-model.number="settings.reserva_garantia" type="number"></label><label class="ts-field"><span>Redondear a</span><input v-model.number="settings.redondeo" type="number"></label><label class="ts-field"><span>Riesgo bajo</span><input v-model.number="settings.riesgo.bajo" type="number"></label><label class="ts-field"><span>Riesgo medio</span><input v-model.number="settings.riesgo.medio" type="number"></label><label class="ts-field"><span>Riesgo alto</span><input v-model.number="settings.riesgo.alto" type="number"></label><label class="ts-field"><span>Riesgo muy alto</span><input v-model.number="settings.riesgo.muy_alto" type="number"></label></div></article>
<div class="ts-quote-layout"><article class="ts-panel ts-form-panel"><div class="ts-panel-heading"><div><span class="ts-panel-kicker">Datos de reparación</span><h3>Nueva cotización</h3></div></div><div class="ts-smart-form"><label class="ts-field"><span>Marca</span><input v-model="form.marca"></label><label class="ts-field ts-field-wide"><span>Modelo *</span><input v-model="form.modelo" placeholder="Ej. Samsung A55"></label><label class="ts-field"><span>Servicio</span><input v-model="form.servicio"></label><label class="ts-field"><span>Calidad / pieza</span><input v-model="form.calidad"></label><label class="ts-field"><span>Costo de pieza *</span><input v-model.number="form.costo_pieza" type="number"></label><label class="ts-field"><span>Envío</span><input v-model.number="form.envio" type="number"></label><label class="ts-field"><span>Nivel de riesgo</span><select v-model="form.riesgo"><option value="bajo">Bajo</option><option value="medio">Medio</option><option value="alto">Alto</option><option value="muy_alto">Muy alto</option></select></label><label class="ts-field"><span>Precio final opcional</span><input v-model.number="form.precio_final" type="number" :placeholder="String(result.recommended)"></label></div><div class="ts-breakdown"><div><span>Pieza + envío</span><strong>{{money(result.direct)}}</strong></div><div><span>Operación</span><strong>{{money(result.operation)}}</strong></div><div><span>Riesgo</span><strong>{{money(result.risk)}}</strong></div><div><span>Garantía</span><strong>{{money(result.warranty)}}</strong></div></div></article>
<aside class="ts-quote-result"><span>PRECIO RECOMENDADO</span><strong>{{money(result.recommended)}}</strong><p>Calculado con margen real, operación y riesgo del trabajo.</p><div class="ts-result-grid"><div><span>Costo real</span><strong>{{money(result.realCost)}}</strong></div><div><span>Precio mínimo</span><strong>{{money(result.minimum)}}</strong></div><div><span>Utilidad</span><strong>{{money(finalPrice-result.realCost)}}</strong></div><div><span>Margen final</span><strong>{{finalMargin.toFixed(1)}}%</strong></div></div><button class="ts-white-button" @click="saveQuote">Guardar cotización</button><button class="ts-outline-light" @click="addRate">Agregar al tarifario</button><button class="ts-outline-light" @click="addInventoryPart">Guardar como refacción</button></aside></div>
<article class="ts-panel"><div class="ts-panel-heading"><div><span class="ts-panel-kicker">Historial</span><h3>Cotizaciones recientes</h3></div></div><div class="ts-history-list"><div v-for="q in quotes.slice(0,12)" :key="q.id"><div><strong>{{q.marca}} {{q.modelo}}</strong><span>{{q.servicio}} · {{q.calidad||'General'}}</span></div><div><strong>{{money(q.precio_final)}}</strong><span>Margen {{Number(q.margen_final||0).toFixed(1)}}%</span></div></div><p v-if="!quotes.length" class="ts-empty-inline">Todavía no hay cotizaciones guardadas.</p></div></article></section></template>
