<script setup>
import { onMounted,ref } from 'vue'
import { aiRepository } from '../repositories/ai.repository'
const data=ref(null),loading=ref(true),error=ref('')
onMounted(async()=>{try{data.value=await aiRepository.contextoNegocio()}catch(e){error.value=e.message}finally{loading.value=false}})
</script>
<template><section class="ts-module-page"><header class="ts-module-header"><div><span class="ts-eyebrow">TechSoul AI</span><h2>Preparación del agente</h2><p>Revisa qué información está lista para alimentar el agente de cotizaciones y atención.</p></div></header><div v-if="error" class="alert alert-danger">{{error}}</div><div v-if="loading" class="ts-panel p-4">Cargando…</div><div v-else class="ai-grid"><article class="ts-panel p-4"><h3>Datos del negocio</h3><strong>{{data.config?.nombre_negocio}}</strong><p>{{data.config?.direccion}}</p><p>{{data.config?.horario||'Horario pendiente'}}</p><span :class="['readiness',data.config?.whatsapp?'ok':'warn']">{{data.config?.whatsapp?'WhatsApp configurado':'Falta WhatsApp'}}</span></article><article class="ts-panel p-4"><h3>Conocimiento disponible</h3><div class="metric"><strong>{{data.faq.length}}</strong><span>Preguntas frecuentes</span></div><div class="metric"><strong>{{data.servicios.length}}</strong><span>Servicios activos</span></div><div class="metric"><strong>{{data.promociones.length}}</strong><span>Promociones activas</span></div></article><article class="ts-panel p-4 full"><h3>Contrato de consulta para el agente</h3><p>El agente debe buscar primero en <code>buscar_conocimiento_ia(termino, limite)</code> y usar la información de <code>configuracion_negocio</code>. No debe inventar precio, disponibilidad, garantía ni tiempo.</p><pre>RPC buscar_conocimiento_ia
Entrada: termino, limite
Salida: tipo, titulo, contenido, categoria, palabras_clave</pre><p class="mb-0">La conexión con WhatsApp se realizará en el siguiente paso mediante Meta WhatsApp Cloud API o un proveedor compatible, usando un backend seguro para las llaves.</p></article></div></section></template>
<style scoped>.ai-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.full{grid-column:1/-1}.metric{display:flex;align-items:baseline;gap:12px;padding:10px 0}.metric strong{font-size:28px}.readiness{display:inline-block;padding:6px 10px;border-radius:99px}.ok{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#92400e}pre{background:#0f172a;color:#e2e8f0;padding:16px;border-radius:12px}@media(max-width:800px){.ai-grid{grid-template-columns:1fr}.full{grid-column:auto}}</style>
