<script setup>
import { computed } from 'vue'
import { getRates, getQuotes, money } from '../lib/pricing'
const rates=getRates(), quotes=getQuotes()
const withCost=rates.filter(r=>r.costo_actual>0)
const avgMargin=computed(()=>withCost.length?withCost.reduce((s,r)=>s+((r.precio_publico-r.costo_actual)/r.precio_publico*100),0)/withCost.length:0)
const low=withCost.filter(r=>((r.precio_publico-r.costo_actual)/r.precio_publico*100)<30)
const top=[...withCost].sort((a,b)=>(b.precio_publico-b.costo_actual)-(a.precio_publico-a.costo_actual)).slice(0,8)
</script>
<template><section class="ts-module-page"><header class="ts-module-header"><div><span class="ts-eyebrow">Centro de inteligencia</span><h2>Rentabilidad de precios</h2><p>Detecta márgenes bajos y descubre qué reparaciones dejan mayor utilidad.</p></div></header><div class="ts-metric-strip ts-metric-strip-four"><article class="ts-mini-metric"><span>Tarifas</span><strong>{{rates.length}}</strong><small>Precios establecidos</small></article><article class="ts-mini-metric"><span>Con costo real</span><strong>{{withCost.length}}</strong><small>Listas para medir utilidad</small></article><article class="ts-mini-metric"><span>Margen promedio</span><strong>{{avgMargin.toFixed(1)}}%</strong><small>Sobre precios con costo</small></article><article class="ts-mini-metric"><span>Requieren atención</span><strong>{{low.length}}</strong><small>Debajo del 30%</small></article></div><div class="ts-insight-grid"><article class="ts-panel ts-insight-card"><div class="ts-panel-heading"><div><span class="ts-panel-kicker">Alertas</span><h3>Márgenes por revisar</h3></div></div><div class="ts-history-list"><div v-for="r in low" :key="r.id"><div><strong>{{r.modelo}} · {{r.calidad}}</strong><span>{{r.servicio}}</span></div><div><strong>{{money(r.precio_publico-r.costo_actual)}}</strong><span>utilidad estimada</span></div></div><p v-if="!low.length" class="ts-empty-inline">Captura costos actuales en Tarifario para activar alertas.</p></div></article><article class="ts-panel ts-insight-card"><div class="ts-panel-heading"><div><span class="ts-panel-kicker">Oportunidades</span><h3>Mayor utilidad por pieza</h3></div></div><div class="ts-history-list"><div v-for="r in top" :key="r.id"><div><strong>{{r.modelo}} · {{r.calidad}}</strong><span>{{r.servicio}}</span></div><div><strong>{{money(r.precio_publico-r.costo_actual)}}</strong><span>utilidad estimada</span></div></div><p v-if="!top.length" class="ts-empty-inline">Agrega el costo actual de compra para ver oportunidades.</p></div></article></div><article class="ts-panel ts-ai-note"><strong>Cómo se vuelve más inteligente</strong><p>Al guardar cotizaciones, compras y costos reales, TechSoul OS podrá comparar cambios de proveedor, margen por modelo y precios que conviene actualizar.</p><span>{{quotes.length}} cotizaciones disponibles para análisis futuro.</span></article></section></template>
