<script setup>
import { computed, onMounted, ref } from 'vue'
import { supabase } from '../lib/supabase'
import { mxn, getBudgets } from '../lib/business'
const loading=ref(true), ventas=ref([]), caja=ref([]), ordenes=ref([]), productos=ref([])
const resumen=computed(()=>{const ingresos=caja.value.filter(x=>x.tipo==='Entrada').reduce((s,x)=>s+Number(x.monto||0),0);const salidas=caja.value.filter(x=>x.tipo==='Salida').reduce((s,x)=>s+Number(x.monto||0),0);const costo=ventas.value.reduce((s,v)=>s+Number(v.costo_total||0),0);return{ingresos,salidas,flujo:ingresos-salidas,ventas:ventas.value.length,ordenes:ordenes.value.length,utilidad:ingresos-salidas-costo,presupuestos:getBudgets().length}})
const dias=computed(()=>{const out=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);const monto=caja.value.filter(x=>String(x.fecha_movimiento||x.created_at||'').slice(0,10)===key&&x.tipo==='Entrada').reduce((s,x)=>s+Number(x.monto||0),0);out.push({label:d.toLocaleDateString('es-MX',{weekday:'short'}),monto})}return out}); const maxDia=computed(()=>Math.max(1,...dias.value.map(x=>x.monto)))
const stockBajo=computed(()=>productos.value.filter(x=>Number(x.stock||0)<=Number(x.stock_minimo||0)).slice(0,8))
async function cargar(){const [v,c,o,p]=await Promise.all([supabase.from('ventas').select('*'),supabase.from('movimientos_caja').select('*'),supabase.from('ordenes').select('*'),supabase.from('productos').select('*')]);ventas.value=v.data||[];caja.value=c.data||[];ordenes.value=o.data||[];productos.value=p.data||[];loading.value=false}
function exportar(){const rows=[['Métrica','Valor'],['Ingresos',resumen.value.ingresos],['Salidas',resumen.value.salidas],['Flujo neto',resumen.value.flujo],['Ventas',resumen.value.ventas],['Órdenes',resumen.value.ordenes],['Presupuestos',resumen.value.presupuestos]];const csv='\uFEFF'+rows.map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`reporte-techsoul-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
onMounted(cargar)
</script><template><section class="ts-module-page"><header class="ts-module-header"><div><span class="ts-eyebrow">Datos reales del sistema</span><h2>Reportes</h2><p>Resumen operativo calculado a partir de ventas, caja, órdenes e inventario.</p></div><button class="ts-action-secondary" @click="exportar">Exportar CSV</button></header><div class="metrics"><article><span>Ingresos</span><strong>{{mxn(resumen.ingresos)}}</strong></article><article><span>Salidas</span><strong>{{mxn(resumen.salidas)}}</strong></article><article><span>Flujo neto</span><strong>{{mxn(resumen.flujo)}}</strong></article><article><span>Órdenes</span><strong>{{resumen.ordenes}}</strong></article><article><span>Ventas</span><strong>{{resumen.ventas}}</strong></article><article><span>Presupuestos</span><strong>{{resumen.presupuestos}}</strong></article></div><div class="report-grid"><article class="ts-panel"><h3>Ingresos de los últimos 7 días</h3><div class="bars"><div v-for="d in dias" :key="d.label"><span :style="{height:`${Math.max(4,(d.monto/maxDia)*100)}%`}" :title="mxn(d.monto)"></span><small>{{d.label}}</small></div></div></article><article class="ts-panel"><h3>Productos con stock bajo</h3><div class="stock"><div v-for="p in stockBajo" :key="p.id"><span>{{p.nombre}}</span><strong>{{p.stock||0}} / mín. {{p.stock_minimo||0}}</strong></div><p v-if="!stockBajo.length">No hay alertas de stock.</p></div></article></div><p v-if="loading">Cargando información…</p></section></template>
<style scoped>.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:18px}.metrics article{background:white;border:1px solid #e5eaf1;border-radius:14px;padding:17px}.metrics span{display:block;color:#667085}.metrics strong{font-size:24px}.report-grid{display:grid;grid-template-columns:1.4fr .8fr;gap:18px}.bars{height:260px;display:flex;align-items:end;gap:16px;padding-top:28px}.bars div{height:100%;flex:1;display:flex;flex-direction:column;justify-content:end;text-align:center}.bars span{display:block;min-height:6px;background:#2161f5;border-radius:8px 8px 2px 2px}.bars small{margin-top:8px;color:#667085}.stock div{display:flex;justify-content:space-between;padding:13px 0;border-bottom:1px solid #edf0f4}@media(max-width:760px){.metrics{grid-template-columns:1fr 1fr}.report-grid{grid-template-columns:1fr}}
</style>
