<script setup>
import { computed, ref } from 'vue'
import { getRates, saveRates, money, normalize } from '../lib/pricing'
const rates = ref(getRates())
const search = ref('')
const category = ref('Todos')
const editing = ref(null)
const form = ref({ marca:'Apple', modelo:'', servicio:'Pantalla', calidad:'INCELL', precio_publico:0, precio_minimo:0, costo_actual:0, activo:true })
const categories = ['Todos','Pantalla','Batería','Tapa','Centro de carga','Cámara','Bocina','Micrófono','Face ID','Placa','Otro']
const filtered = computed(() => rates.value.filter(r => (category.value === 'Todos' || r.servicio === category.value) && (!search.value || [r.marca,r.modelo,r.servicio,r.calidad].some(v => normalize(v).includes(normalize(search.value))))))
const alerts = computed(() => rates.value.filter(r => r.costo_actual > 0 && ((r.precio_publico-r.costo_actual)/r.precio_publico*100) < 30).length)
function reset(){ editing.value=null; form.value={ marca:'Apple', modelo:'', servicio:'Pantalla', calidad:'INCELL', precio_publico:0, precio_minimo:0, costo_actual:0, activo:true } }
function edit(row){ editing.value=row.id; form.value={...row}; window.scrollTo({top:0,behavior:'smooth'}) }
function save(){ if(!form.value.modelo || !form.value.precio_publico) return alert('Captura modelo y precio público'); const rows=[...rates.value]; if(editing.value){ const i=rows.findIndex(r=>r.id===editing.value); rows[i]={...rows[i],...form.value,actualizado_en:new Date().toISOString()} } else rows.unshift({...form.value,id:crypto.randomUUID(),actualizado_en:new Date().toISOString(),origen:'Manual'}); rates.value=saveRates(rows); reset() }
function remove(id){ if(!confirm('¿Eliminar este precio del tarifario?')) return; rates.value=saveRates(rates.value.filter(r=>r.id!==id)) }
function margin(r){ return r.precio_publico ? Math.round(((r.precio_publico-r.costo_actual)/r.precio_publico)*100) : 0 }
</script>
<template><section class="ts-module-page">
<header class="ts-module-header"><div><span class="ts-eyebrow">Precios establecidos</span><h2>Tarifario TechSoul</h2><p>Consulta, edita y controla tus precios públicos y mínimos.</p></div><button class="ts-action-primary" @click="reset">Nuevo precio</button></header>
<div class="ts-metric-strip ts-metric-strip-four"><article class="ts-mini-metric"><span>Precios activos</span><strong>{{rates.length}}</strong><small>Pantallas, baterías y más</small></article><article class="ts-mini-metric"><span>Pantallas</span><strong>{{rates.filter(r=>r.servicio==='Pantalla').length}}</strong><small>Opciones por modelo y calidad</small></article><article class="ts-mini-metric"><span>Baterías</span><strong>{{rates.filter(r=>r.servicio==='Batería').length}}</strong><small>Premium y alta capacidad</small></article><article class="ts-mini-metric"><span>Alertas de margen</span><strong>{{alerts}}</strong><small>Debajo de 30% con costo capturado</small></article></div>
<article class="ts-panel ts-form-panel"><div class="ts-panel-heading"><div><span class="ts-panel-kicker">{{editing?'Editar':'Nuevo'}} registro</span><h3>Precio del tarifario</h3></div><button v-if="editing" class="ts-action-secondary" @click="reset">Cancelar edición</button></div><form class="ts-smart-form" @submit.prevent="save"><label class="ts-field"><span>Marca</span><input v-model="form.marca"></label><label class="ts-field ts-field-wide"><span>Modelo *</span><input v-model="form.modelo" placeholder="Ej. Samsung A55"></label><label class="ts-field"><span>Servicio</span><select v-model="form.servicio"><option v-for="c in categories.slice(1)" :key="c">{{c}}</option></select></label><label class="ts-field"><span>Calidad / tipo</span><input v-model="form.calidad" placeholder="OLED, INCELL, alta capacidad..."></label><label class="ts-field"><span>Precio público *</span><input v-model.number="form.precio_publico" type="number" min="0"></label><label class="ts-field"><span>Precio mínimo</span><input v-model.number="form.precio_minimo" type="number" min="0"></label><label class="ts-field"><span>Costo actual de compra</span><input v-model.number="form.costo_actual" type="number" min="0"></label><div class="ts-form-actions ts-field-full"><button class="ts-action-primary" type="submit">{{editing?'Guardar cambios':'Agregar al tarifario'}}</button></div></form></article>
<article class="ts-panel"><div class="ts-orders-toolbar"><label class="ts-search-control ts-search-grow"><input v-model="search" placeholder="Buscar modelo, calidad o servicio..."></label><select v-model="category" class="ts-filter-select"><option v-for="c in categories" :key="c">{{c}}</option></select></div><div class="ts-price-grid"><article v-for="r in filtered" :key="r.id" class="ts-price-card"><div class="ts-price-card-top"><div><span>{{r.marca}} · {{r.servicio}}</span><h3>{{r.modelo}}</h3><p>{{r.calidad || 'Sin variante'}}</p></div><span class="ts-margin-badge" :class="{'warning':r.costo_actual&&margin(r)<30}">{{r.costo_actual?margin(r)+'%':'Tarifa'}}</span></div><div class="ts-price-values"><div><span>Precio público</span><strong>{{money(r.precio_publico)}}</strong></div><div><span>Precio mínimo</span><strong>{{money(r.precio_minimo)}}</strong></div><div><span>Costo actual</span><strong>{{r.costo_actual?money(r.costo_actual):'Sin capturar'}}</strong></div></div><div class="ts-card-actions"><button class="ts-action-secondary" @click="edit(r)">Editar</button><button class="ts-danger-button" @click="remove(r.id)">Eliminar</button></div></article></div></article>
</section></template>
