<script setup>
import { computed,onMounted,ref } from 'vue'
import { adminRepository } from '../repositories/admin.repository'
const usuarios=ref([]),roles=ref([]),permisos=ref([]),loading=ref(true),error=ref(''),ok=ref(''),tab=ref('usuarios')
const porRol=computed(()=>roles.value.map(r=>({...r,permisos:permisos.value.filter(p=>p.rol_clave===r.clave)})))
async function cargar(){loading.value=true;error.value='';try{[usuarios.value,roles.value,permisos.value]=await Promise.all([adminRepository.usuarios(),adminRepository.roles(),adminRepository.permisos()])}catch(e){error.value=e.message}finally{loading.value=false}}
async function guardarUsuario(u){try{await adminRepository.guardarUsuario(u);ok.value='Usuario actualizado';setTimeout(()=>ok.value='',2200)}catch(e){error.value=e.message}}
async function guardarPermiso(p){try{await adminRepository.guardarPermiso(p);ok.value='Permiso actualizado';setTimeout(()=>ok.value='',1500)}catch(e){error.value=e.message}}
onMounted(cargar)
</script>
<template><section class="ts-module-page"><header class="ts-module-header"><div><span class="ts-eyebrow">Accesos y seguridad</span><h2>Usuarios, roles y permisos</h2><p>Administra perfiles existentes de Supabase Auth y limita las acciones por rol.</p></div></header>
<div v-if="error" class="alert alert-danger">{{error}}</div><div v-if="ok" class="alert alert-success">{{ok}}</div>
<div class="admin-tabs"><button :class="{active:tab==='usuarios'}" @click="tab='usuarios'">Usuarios</button><button :class="{active:tab==='permisos'}" @click="tab='permisos'">Matriz de permisos</button></div>
<div v-if="loading" class="ts-panel p-4">Cargando…</div>
<div v-else-if="tab==='usuarios'" class="ts-panel p-4 users-panel"><div class="table-responsive users-table-wrap"><table class="table align-middle users-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Puesto</th><th>Teléfono</th><th>Activo</th><th></th></tr></thead><tbody><tr v-for="u in usuarios" :key="u.id"><td data-label="Usuario" class="user-identity"><strong>{{u.nombre}}</strong><small class="d-block text-muted">{{u.email}}</small></td><td data-label="Rol"><select v-model="u.rol" class="form-select"><option v-for="r in roles" :key="r.clave" :value="r.clave">{{r.nombre}}</option></select></td><td data-label="Puesto"><input v-model="u.puesto" class="form-control" placeholder="Recepción / Técnico"></td><td data-label="Teléfono"><input v-model="u.telefono" class="form-control"></td><td data-label="Activo" class="active-cell"><input v-model="u.activo" type="checkbox" class="form-check-input"></td><td data-label="Acciones" class="user-save-cell"><button class="btn btn-primary btn-sm user-save" @click="guardarUsuario(u)">Guardar</button></td></tr></tbody></table></div><p class="text-muted mb-0">Para invitar un usuario nuevo, créalo primero en Supabase → Authentication → Users. Después aparecerá aquí automáticamente.</p></div>
<div v-else class="role-grid permissions-grid"><article v-for="r in porRol" :key="r.clave" class="ts-panel p-4"><h3>{{r.nombre}}</h3><p class="text-muted">{{r.descripcion}}</p><div class="table-responsive permissions-table-wrap"><table class="table table-sm align-middle permissions-table"><thead><tr><th>Módulo</th><th>Ver</th><th>Crear</th><th>Editar</th><th>Eliminar</th><th>Cobrar</th><th></th></tr></thead><tbody><tr v-for="p in r.permisos" :key="p.id"><td data-label="Módulo" class="permission-module">{{p.modulo}}</td><td data-label="Ver"><input v-model="p.puede_ver" type="checkbox"></td><td data-label="Crear"><input v-model="p.puede_crear" type="checkbox"></td><td data-label="Editar"><input v-model="p.puede_editar" type="checkbox"></td><td data-label="Eliminar"><input v-model="p.puede_eliminar" type="checkbox"></td><td data-label="Cobrar"><input v-model="p.puede_cobrar" type="checkbox"></td><td data-label="Acciones" class="permission-save"><button class="btn btn-outline-primary btn-sm" @click="guardarPermiso(p)">Guardar</button></td></tr></tbody></table></div></article></div></section></template>
<style scoped>
.admin-tabs{display:flex;gap:8px;margin-bottom:18px;overflow-x:auto;scrollbar-width:none}.admin-tabs::-webkit-scrollbar{display:none}.admin-tabs button{flex:0 0 auto;border:1px solid var(--ts-border);background:var(--ts-surface);color:var(--ts-text);padding:10px 16px;border-radius:10px;font-weight:700}.admin-tabs button.active{background:var(--ts-primary);border-color:var(--ts-primary);color:#fff}.role-grid{display:grid;gap:18px}.table input[type=checkbox]{width:18px;height:18px}
@media(max-width:700px){
  .ts-module-page{min-width:0}.ts-module-header h2{font-size:1.85rem;line-height:1.08}.ts-module-header p{font-size:.95rem;line-height:1.5}.admin-tabs{margin-inline:-2px}.admin-tabs button{min-height:46px;padding:10px 14px;font-size:.95rem}.users-panel{padding:12px!important}.users-table-wrap,.permissions-table-wrap{overflow:visible}.users-table thead,.permissions-table thead{display:none}.users-table,.users-table tbody,.permissions-table,.permissions-table tbody{display:block;width:100%}.users-table tr,.permissions-table tr{display:grid;width:100%;margin-bottom:12px;padding:16px;border:1px solid var(--ts-border);border-radius:16px;background:var(--ts-surface-2);box-shadow:var(--ts-shadow-sm)}.users-table td,.permissions-table td{display:grid!important;grid-template-columns:92px minmax(0,1fr);align-items:center;gap:10px;width:100%!important;min-width:0!important;padding:8px 0!important;border:0!important}.users-table td::before,.permissions-table td::before{content:attr(data-label);color:var(--ts-muted);font-size:.76rem;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.users-table .user-identity{display:block!important;padding-bottom:12px!important;margin-bottom:4px;border-bottom:1px solid var(--ts-border)!important}.users-table .user-identity::before{display:none}.user-identity strong{display:block;font-size:1rem}.user-identity small{margin-top:2px;font-size:.82rem;overflow-wrap:anywhere}.users-table select,.users-table input:not([type=checkbox]){width:100%;min-width:0;min-height:46px;font-size:16px}.users-table .active-cell{grid-template-columns:92px 1fr}.users-table .active-cell input{justify-self:start;width:23px;height:23px}.users-table .user-save-cell,.permissions-table .permission-save{grid-template-columns:1fr;padding-top:12px!important}.users-table .user-save-cell::before,.permissions-table .permission-save::before{display:none}.user-save,.permission-save button{width:100%;min-height:44px}.permissions-grid article{padding:14px!important}.permissions-grid h3{font-size:1.1rem}.permissions-table tr{grid-template-columns:1fr 1fr;gap:4px 12px}.permissions-table td{grid-template-columns:1fr auto;padding:8px!important;border-bottom:1px solid color-mix(in srgb,var(--ts-border) 65%,transparent)!important}.permissions-table .permission-module{grid-column:1/-1;display:block!important;padding:4px 8px 12px!important;font-size:1rem;font-weight:800;border-bottom:1px solid var(--ts-border)!important}.permissions-table .permission-module::before{display:none}.permissions-table td input[type=checkbox]{width:22px;height:22px}.permissions-table .permission-save{grid-column:1/-1;border-bottom:0!important}.permissions-table td::before{font-size:.72rem}
}
:global(:root[data-theme='dark']) .admin-tabs button{background:var(--ts-surface);border-color:var(--ts-border);color:var(--ts-text)}:global(:root[data-theme='dark']) .admin-tabs button.active{background:var(--ts-primary);color:#fff}:global(:root[data-theme='dark']) .users-table tr,:global(:root[data-theme='dark']) .permissions-table tr{background:var(--ts-surface-2)}
</style>