<script setup>
import { computed,onMounted,ref } from 'vue'
import { adminRepository } from '../repositories/admin.repository'
const usuarios=ref([]),roles=ref([]),permisos=ref([]),loading=ref(true),error=ref(''),ok=ref(''),tab=ref('usuarios')
const porRol=computed(()=>roles.value.map(r=>({...r,permisos:permisos.value.filter(p=>p.rol_clave===r.clave)})))
async function cargar(){loading.value=true;error.value='';try{[usuarios.value,roles.value,permisos.value]=await Promise.all([adminRepository.usuarios(),adminRepository.roles(),adminRepository.permisos()])}catch(e){error.value=e.message}finally{loading.value=false}}
async function guardarUsuario(u){try{await adminRepository.guardarUsuario(u);ok.value='Usuario actualizado';setTimeout(()=>ok.value='',2200)}catch(e){error.value=e.message}}
async function guardarPermiso(p){try{await adminRepository.guardarPermiso(p);ok.value='Permiso actualizado';setTimeout(()=>ok.value='',1500)}catch(e){error.value=e.message}}
onMounted(cargar)
</script>
<template><section class="ts-module-page"><header class="ts-module-header"><div><span class="ts-eyebrow">Accesos y seguridad</span><h2>Usuarios, roles y permisos</h2><p>Administra perfiles existentes de Supabase Auth y limita las acciones por rol.</p></div></header>
<div v-if="error" class="alert alert-danger">{{error}}</div><div v-if="ok" class="alert alert-success">{{ok}}</div>
<div class="admin-tabs"><button :class="{active:tab==='usuarios'}" @click="tab='usuarios'">Usuarios</button><button :class="{active:tab==='permisos'}" @click="tab='permisos'">Matriz de permisos</button></div>
<div v-if="loading" class="ts-panel p-4">Cargando…</div>
<div v-else-if="tab==='usuarios'" class="ts-panel p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Usuario</th><th>Rol</th><th>Puesto</th><th>Teléfono</th><th>Activo</th><th></th></tr></thead><tbody><tr v-for="u in usuarios" :key="u.id"><td><strong>{{u.nombre}}</strong><small class="d-block text-muted">{{u.email}}</small></td><td><select v-model="u.rol" class="form-select"><option v-for="r in roles" :key="r.clave" :value="r.clave">{{r.nombre}}</option></select></td><td><input v-model="u.puesto" class="form-control" placeholder="Recepción / Técnico"></td><td><input v-model="u.telefono" class="form-control"></td><td><input v-model="u.activo" type="checkbox" class="form-check-input"></td><td><button class="btn btn-primary btn-sm" @click="guardarUsuario(u)">Guardar</button></td></tr></tbody></table></div><p class="text-muted mb-0">Para invitar un usuario nuevo, créalo primero en Supabase → Authentication → Users. Después aparecerá aquí automáticamente.</p></div>
<div v-else class="role-grid"><article v-for="r in porRol" :key="r.clave" class="ts-panel p-4"><h3>{{r.nombre}}</h3><p class="text-muted">{{r.descripcion}}</p><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Módulo</th><th>Ver</th><th>Crear</th><th>Editar</th><th>Eliminar</th><th>Cobrar</th><th></th></tr></thead><tbody><tr v-for="p in r.permisos" :key="p.id"><td>{{p.modulo}}</td><td><input v-model="p.puede_ver" type="checkbox"></td><td><input v-model="p.puede_crear" type="checkbox"></td><td><input v-model="p.puede_editar" type="checkbox"></td><td><input v-model="p.puede_eliminar" type="checkbox"></td><td><input v-model="p.puede_cobrar" type="checkbox"></td><td><button class="btn btn-outline-primary btn-sm" @click="guardarPermiso(p)">Guardar</button></td></tr></tbody></table></div></article></div></section></template>
<style scoped>.admin-tabs{display:flex;gap:8px;margin-bottom:18px}.admin-tabs button{border:1px solid #dbe3f1;background:#fff;padding:10px 16px;border-radius:10px;font-weight:700}.admin-tabs button.active{background:#2563eb;color:white}.role-grid{display:grid;gap:18px}.table input[type=checkbox]{width:18px;height:18px}</style>
