-- TechSoul OS · Sprint 02
-- Clientes + Equipos en Supabase
-- Ejecutar UNA VEZ en Supabase > SQL Editor, después de production_foundation.sql.

begin;

-- Función reutilizable para mantener updated_at.
create or replace function public.actualizar_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  whatsapp text,
  correo text,
  notas text,
  activo boolean not null default true,
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clientes_nombre_no_vacio check (length(trim(nombre)) > 0)
);

create index if not exists clientes_nombre_idx on public.clientes using btree (lower(nombre));
create index if not exists clientes_telefono_idx on public.clientes (telefono);
create index if not exists clientes_whatsapp_idx on public.clientes (whatsapp);
create index if not exists clientes_correo_idx on public.clientes using btree (lower(correo));

create table if not exists public.equipos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on update cascade on delete restrict,
  tipo_equipo text not null default 'Celular',
  marca text,
  modelo text not null,
  color text,
  imei_serie text,
  codigo_bloqueo text,
  observaciones text,
  activo boolean not null default true,
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint equipos_tipo_no_vacio check (length(trim(tipo_equipo)) > 0),
  constraint equipos_modelo_no_vacio check (length(trim(modelo)) > 0)
);

create index if not exists equipos_cliente_id_idx on public.equipos (cliente_id);
create index if not exists equipos_modelo_idx on public.equipos using btree (lower(modelo));
create index if not exists equipos_imei_serie_idx on public.equipos using btree (lower(imei_serie));

-- Evita duplicar un IMEI/serie real, pero permite varios registros vacíos.
create unique index if not exists equipos_imei_serie_unico_idx
on public.equipos (lower(trim(imei_serie)))
where imei_serie is not null and length(trim(imei_serie)) > 0;

drop trigger if exists clientes_actualizar_updated_at on public.clientes;
create trigger clientes_actualizar_updated_at
before update on public.clientes
for each row execute function public.actualizar_updated_at();

drop trigger if exists equipos_actualizar_updated_at on public.equipos;
create trigger equipos_actualizar_updated_at
before update on public.equipos
for each row execute function public.actualizar_updated_at();

alter table public.clientes enable row level security;
alter table public.equipos enable row level security;

-- Clientes
DROP POLICY IF EXISTS clientes_leer ON public.clientes;
CREATE POLICY clientes_leer ON public.clientes
FOR SELECT TO authenticated
USING (public.mi_rol() IS NOT NULL);

DROP POLICY IF EXISTS clientes_insertar ON public.clientes;
CREATE POLICY clientes_insertar ON public.clientes
FOR INSERT TO authenticated
WITH CHECK (public.mi_rol() IN ('admin','recepcion','tecnico'));

DROP POLICY IF EXISTS clientes_actualizar ON public.clientes;
CREATE POLICY clientes_actualizar ON public.clientes
FOR UPDATE TO authenticated
USING (public.mi_rol() IN ('admin','recepcion','tecnico'))
WITH CHECK (public.mi_rol() IN ('admin','recepcion','tecnico'));

DROP POLICY IF EXISTS clientes_eliminar ON public.clientes;
CREATE POLICY clientes_eliminar ON public.clientes
FOR DELETE TO authenticated
USING (public.es_admin());

-- Equipos
DROP POLICY IF EXISTS equipos_leer ON public.equipos;
CREATE POLICY equipos_leer ON public.equipos
FOR SELECT TO authenticated
USING (public.mi_rol() IS NOT NULL);

DROP POLICY IF EXISTS equipos_insertar ON public.equipos;
CREATE POLICY equipos_insertar ON public.equipos
FOR INSERT TO authenticated
WITH CHECK (public.mi_rol() IN ('admin','recepcion','tecnico'));

DROP POLICY IF EXISTS equipos_actualizar ON public.equipos;
CREATE POLICY equipos_actualizar ON public.equipos
FOR UPDATE TO authenticated
USING (public.mi_rol() IN ('admin','recepcion','tecnico'))
WITH CHECK (public.mi_rol() IN ('admin','recepcion','tecnico'));

DROP POLICY IF EXISTS equipos_eliminar ON public.equipos;
CREATE POLICY equipos_eliminar ON public.equipos
FOR DELETE TO authenticated
USING (public.es_admin());

grant select, insert, update, delete on public.clientes to authenticated;
grant select, insert, update, delete on public.equipos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Vista de expediente básico. Será reutilizada por órdenes, garantías e IA.
create or replace view public.expediente_equipos
with (security_invoker = true)
as
select
  e.id,
  e.cliente_id,
  c.nombre as cliente_nombre,
  c.telefono as cliente_telefono,
  c.whatsapp as cliente_whatsapp,
  e.tipo_equipo,
  e.marca,
  e.modelo,
  e.color,
  e.imei_serie,
  e.observaciones,
  e.activo,
  e.created_at,
  e.updated_at
from public.equipos e
join public.clientes c on c.id = e.cliente_id;

grant select on public.expediente_equipos to authenticated;

commit;
