-- TechSoul OS · Sprints 1 y 2: catálogo maestro + inventario inteligente
create table if not exists public.catalogo_servicios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null default 'Otro',
  descripcion text,
  marca text,
  modelo text,
  variante text,
  costo_base numeric(12,2) not null default 0,
  precio_venta numeric(12,2) not null default 0,
  garantia_dias integer not null default 90,
  activo boolean not null default true,
  notas text,
  producto_id bigint references public.productos(id) on delete set null,
  cantidad_producto numeric(12,2) not null default 1,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

alter table public.productos add column if not exists sku text;
alter table public.productos add column if not exists codigo_barras text;
alter table public.productos add column if not exists activo boolean not null default true;
alter table public.productos add column if not exists actualizado_en timestamptz not null default now();
create unique index if not exists productos_sku_unico on public.productos(sku) where sku is not null and sku <> '';
create index if not exists catalogo_servicios_busqueda on public.catalogo_servicios(categoria, marca, modelo, activo);
create index if not exists movimientos_inventario_producto on public.movimientos_inventario(producto_id);

alter table public.catalogo_servicios enable row level security;
drop policy if exists "catalogo_servicios_select" on public.catalogo_servicios;
drop policy if exists "catalogo_servicios_insert" on public.catalogo_servicios;
drop policy if exists "catalogo_servicios_update" on public.catalogo_servicios;
drop policy if exists "catalogo_servicios_delete" on public.catalogo_servicios;
create policy "catalogo_servicios_select" on public.catalogo_servicios for select to authenticated using (true);
create policy "catalogo_servicios_insert" on public.catalogo_servicios for insert to authenticated with check (true);
create policy "catalogo_servicios_update" on public.catalogo_servicios for update to authenticated using (true) with check (true);
create policy "catalogo_servicios_delete" on public.catalogo_servicios for delete to authenticated using (true);

insert into public.catalogo_servicios (nombre,categoria,garantia_dias,activo)
select * from (values
 ('Cambio de pantalla','Pantallas',90,true),('Cambio de batería','Baterías',90,true),
 ('Centro de carga','Centros de carga',90,true),('Tapa trasera','Tapas',90,true),
 ('Reparación por humedad','Humedad',90,true),('Diagnóstico','Diagnóstico',0,true)
) as seed(nombre,categoria,garantia_dias,activo)
where not exists (select 1 from public.catalogo_servicios);
