-- TechSoul OS · Sprint 05
-- Ventas, detalle, caja, presupuestos y configuración del negocio.
-- Ejecutar después del Sprint 04.

begin;

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  cliente_nombre text not null default 'Público general',
  cliente_telefono text default '',
  total numeric(12,2) not null default 0 check (total >= 0),
  anticipo numeric(12,2) not null default 0 check (anticipo >= 0),
  pagado numeric(12,2) not null default 0 check (pagado >= 0),
  saldo numeric(12,2) not null default 0 check (saldo >= 0),
  metodo_pago text default 'Efectivo',
  estado_pago text not null default 'Pendiente',
  estado_entrega text not null default 'Entregado',
  notas text default '',
  fecha_venta timestamptz not null default now(),
  presupuesto_id bigint,
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ventas_montos_validos check (pagado <= total and anticipo <= total)
);
create index if not exists ventas_fecha_idx on public.ventas(fecha_venta desc);
create index if not exists ventas_estado_pago_idx on public.ventas(estado_pago);

create table if not exists public.detalle_ventas (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.ventas(id) on delete cascade,
  tipo_item text not null default 'producto',
  producto_id bigint references public.productos(id) on delete set null,
  descripcion text not null,
  cantidad numeric(12,2) not null default 1 check (cantidad > 0),
  precio_unitario numeric(12,2) not null default 0 check (precio_unitario >= 0),
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  costo_estimado numeric(12,2) not null default 0 check (costo_estimado >= 0),
  proveedor text default '',
  fecha_estimada date,
  estado_entrega text not null default 'entregado',
  notas text default '',
  created_at timestamptz not null default now()
);
create index if not exists detalle_ventas_venta_idx on public.detalle_ventas(venta_id);

create table if not exists public.movimientos_caja (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('Entrada','Salida')),
  concepto text not null,
  monto numeric(12,2) not null check (monto > 0),
  metodo_pago text default 'Efectivo',
  referencia_tipo text,
  referencia_id text,
  notas text default '',
  fecha_movimiento timestamptz not null default now(),
  usuario_id uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists movimientos_caja_fecha_idx on public.movimientos_caja(fecha_movimiento desc);
create index if not exists movimientos_caja_ref_idx on public.movimientos_caja(referencia_tipo,referencia_id);

create table if not exists public.presupuestos (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  cliente text not null,
  telefono text default '',
  equipo text not null,
  conceptos jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0 check (total >= 0),
  estado text not null default 'Borrador',
  notas text default '',
  orden_id bigint references public.ordenes(id) on delete set null,
  venta_id bigint references public.ventas(id) on delete set null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists presupuestos_estado_idx on public.presupuestos(estado);
create index if not exists presupuestos_fecha_idx on public.presupuestos(creado_en desc);

-- Enlaces que no pudieron crearse antes porque las tablas aún no existían.
do $$ begin
 if not exists (select 1 from pg_constraint where conname='ordenes_presupuesto_id_fkey') then
  alter table public.ordenes add constraint ordenes_presupuesto_id_fkey foreign key(presupuesto_id) references public.presupuestos(id) on delete set null;
 end if;
 if not exists (select 1 from pg_constraint where conname='solicitudes_compra_venta_id_fkey') then
  alter table public.solicitudes_compra add constraint solicitudes_compra_venta_id_fkey foreign key(venta_id) references public.ventas(id) on delete set null;
 end if;
end $$;

create table if not exists public.configuracion_negocio (
  id bigint generated by default as identity primary key,
  nombre_negocio text not null default 'TechSoul',
  telefono text default '',
  whatsapp text default '',
  direccion text default '',
  correo text default '',
  sitio_web text default '',
  logo_url text default '',
  condiciones_generales text default '',
  fecha_actualizacion timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
insert into public.configuracion_negocio(nombre_negocio,telefono,whatsapp,direccion)
select 'TechSoul','6677487373','6677487373','Blvd. Jardín de las Orquídeas 2584-B, Santa Fe, Culiacán'
where not exists(select 1 from public.configuracion_negocio);

-- Triggers.
do $$ declare t text; begin
 foreach t in array array['ventas','configuracion_negocio'] loop
  execute format('drop trigger if exists %I on public.%I',t||'_actualizar_updated_at',t);
  execute format('create trigger %I before update on public.%I for each row execute function public.actualizar_updated_at()',t||'_actualizar_updated_at',t);
 end loop;
end $$;

-- RLS: caja y configuración solo admin/recepción para escritura.
do $$ declare t text; begin
 foreach t in array array['ventas','detalle_ventas','presupuestos'] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('drop policy if exists %I on public.%I',t||'_leer',t);
  execute format('create policy %I on public.%I for select to authenticated using (public.mi_rol() is not null)',t||'_leer',t);
  execute format('drop policy if exists %I on public.%I',t||'_insertar',t);
  execute format('create policy %I on public.%I for insert to authenticated with check (public.mi_rol() in (''admin'',''recepcion'',''tecnico''))',t||'_insertar',t);
  execute format('drop policy if exists %I on public.%I',t||'_actualizar',t);
  execute format('create policy %I on public.%I for update to authenticated using (public.mi_rol() in (''admin'',''recepcion'',''tecnico'')) with check (public.mi_rol() in (''admin'',''recepcion'',''tecnico''))',t||'_actualizar',t);
  execute format('drop policy if exists %I on public.%I',t||'_eliminar',t);
  execute format('create policy %I on public.%I for delete to authenticated using (public.es_admin())',t||'_eliminar',t);
  execute format('grant select,insert,update,delete on public.%I to authenticated',t);
 end loop;
end $$;

alter table public.movimientos_caja enable row level security;
drop policy if exists movimientos_caja_leer on public.movimientos_caja;
create policy movimientos_caja_leer on public.movimientos_caja for select to authenticated using (public.mi_rol() in ('admin','recepcion'));
drop policy if exists movimientos_caja_insertar on public.movimientos_caja;
create policy movimientos_caja_insertar on public.movimientos_caja for insert to authenticated with check (public.mi_rol() in ('admin','recepcion','tecnico'));
drop policy if exists movimientos_caja_actualizar on public.movimientos_caja;
create policy movimientos_caja_actualizar on public.movimientos_caja for update to authenticated using (public.mi_rol() in ('admin','recepcion')) with check (public.mi_rol() in ('admin','recepcion'));
drop policy if exists movimientos_caja_eliminar on public.movimientos_caja;
create policy movimientos_caja_eliminar on public.movimientos_caja for delete to authenticated using (public.es_admin());
grant select,insert,update,delete on public.movimientos_caja to authenticated;

alter table public.configuracion_negocio enable row level security;
drop policy if exists configuracion_negocio_leer on public.configuracion_negocio;
create policy configuracion_negocio_leer on public.configuracion_negocio for select to authenticated using (public.mi_rol() is not null);
drop policy if exists configuracion_negocio_escribir on public.configuracion_negocio;
create policy configuracion_negocio_escribir on public.configuracion_negocio for all to authenticated using (public.mi_rol() in ('admin','recepcion')) with check (public.mi_rol() in ('admin','recepcion'));
grant select,insert,update,delete on public.configuracion_negocio to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into storage.buckets(id,name,public)
values ('logos','logos',true)
on conflict(id) do update set public=true;

commit;
