-- TechSoul OS · Sprint 3 y 4: Compras, caja y dashboard
begin;

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  whatsapp text,
  email text,
  notas text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ordenes_compra (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  proveedor_id bigint references public.proveedores(id) on delete set null,
  estado text not null default 'Pendiente' check (estado in ('Pendiente','Recibida','Cancelada')),
  metodo_pago text not null default 'Efectivo',
  subtotal numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  notas text,
  fecha_orden timestamptz not null default now(),
  fecha_recepcion timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ordenes_compra_detalle (
  id bigint generated by default as identity primary key,
  orden_compra_id bigint not null references public.ordenes_compra(id) on delete cascade,
  producto_id bigint references public.productos(id) on delete set null,
  descripcion text not null,
  cantidad numeric(12,2) not null default 1 check (cantidad > 0),
  costo_unitario numeric(12,2) not null default 0 check (costo_unitario >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.movimientos_caja (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('Entrada','Salida')),
  concepto text not null,
  monto numeric(12,2) not null check (monto > 0),
  metodo_pago text not null default 'Efectivo',
  referencia_tipo text,
  referencia_id bigint,
  notas text,
  fecha_movimiento timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_oc_proveedor on public.ordenes_compra(proveedor_id);
create index if not exists idx_oc_estado on public.ordenes_compra(estado);
create index if not exists idx_oc_fecha on public.ordenes_compra(fecha_orden desc);
create index if not exists idx_oc_detalle_orden on public.ordenes_compra_detalle(orden_compra_id);
create index if not exists idx_mov_caja_fecha on public.movimientos_caja(fecha_movimiento desc);
create index if not exists idx_mov_caja_tipo on public.movimientos_caja(tipo);
create unique index if not exists idx_mov_caja_referencia_unica
  on public.movimientos_caja(tipo, referencia_tipo, referencia_id, concepto)
  where referencia_tipo is not null and referencia_id is not null;

-- Vista útil para reportes y dashboard.
create or replace view public.resumen_caja_diario as
select
  date(fecha_movimiento at time zone 'America/Mazatlan') as fecha,
  coalesce(sum(monto) filter (where tipo = 'Entrada'), 0) as ingresos,
  coalesce(sum(monto) filter (where tipo = 'Salida'), 0) as salidas,
  coalesce(sum(case when tipo = 'Entrada' then monto else -monto end), 0) as balance
from public.movimientos_caja
group by 1;

-- RLS. Estas políticas siguen los roles ya usados por TechSoul OS.
do $$
declare t text;
begin
  foreach t in array array['proveedores','ordenes_compra','ordenes_compra_detalle','movimientos_caja'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_leer', t);
    execute format('create policy %I on public.%I for select to authenticated using (public.mi_rol() is not null)', t || '_leer', t);
    execute format('drop policy if exists %I on public.%I', t || '_insertar', t);
    execute format('create policy %I on public.%I for insert to authenticated with check (public.mi_rol() in (''admin'',''recepcion'',''tecnico''))', t || '_insertar', t);
    execute format('drop policy if exists %I on public.%I', t || '_actualizar', t);
    execute format('create policy %I on public.%I for update to authenticated using (public.mi_rol() in (''admin'',''recepcion'',''tecnico'')) with check (public.mi_rol() in (''admin'',''recepcion'',''tecnico''))', t || '_actualizar', t);
    execute format('drop policy if exists %I on public.%I', t || '_eliminar', t);
    execute format('create policy %I on public.%I for delete to authenticated using (public.es_admin())', t || '_eliminar', t);
  end loop;
end $$;

grant select on public.resumen_caja_diario to authenticated;

commit;
