-- TechSoul OS · Entregas 4 y 5
-- Administración, roles/permisos, auditoría y preparación de conocimiento para IA.

create table if not exists public.roles_sistema (
  clave text primary key,
  nombre text not null,
  descripcion text not null default '',
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.permisos_sistema (
  id bigint generated by default as identity primary key,
  rol_clave text not null references public.roles_sistema(clave) on update cascade on delete cascade,
  modulo text not null,
  puede_ver boolean not null default false,
  puede_crear boolean not null default false,
  puede_editar boolean not null default false,
  puede_eliminar boolean not null default false,
  puede_cobrar boolean not null default false,
  actualizado_en timestamptz not null default now(),
  unique (rol_clave, modulo)
);

create table if not exists public.metodos_pago_config (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true,
  requiere_referencia boolean not null default false,
  orden integer not null default 0,
  creado_en timestamptz not null default now()
);

alter table public.perfiles add column if not exists telefono text;
alter table public.perfiles add column if not exists puesto text;
alter table public.perfiles add column if not exists actualizado_en timestamptz not null default now();
alter table public.catalogo_servicios add column if not exists preguntas_frecuentes text;
alter table public.catalogo_servicios add column if not exists instrucciones_agente text;

insert into public.roles_sistema (clave,nombre,descripcion) values
 ('admin','Administrador','Acceso total al sistema.'),
 ('recepcion','Recepción','Clientes, órdenes, cobros y operación diaria.'),
 ('tecnico','Técnico','Órdenes, equipos, diagnóstico y garantías.')
on conflict (clave) do update set nombre=excluded.nombre, descripcion=excluded.descripcion;

insert into public.permisos_sistema (rol_clave,modulo,puede_ver,puede_crear,puede_editar,puede_eliminar,puede_cobrar)
select r.clave, m.modulo,
  true,
  case when r.clave='admin' then true when r.clave='recepcion' then m.modulo not in ('usuarios','configuracion','auditoria') else m.modulo in ('ordenes','equipos','garantias') end,
  case when r.clave='admin' then true when r.clave='recepcion' then m.modulo not in ('usuarios','configuracion','auditoria') else m.modulo in ('ordenes','equipos','garantias') end,
  r.clave='admin',
  r.clave in ('admin','recepcion') and m.modulo in ('ordenes','caja','ventas')
from public.roles_sistema r
cross join (values ('dashboard'),('clientes'),('equipos'),('ordenes'),('inventario'),('compras'),('ventas'),('caja'),('reportes'),('garantias'),('catalogo'),('conocimiento'),('usuarios'),('configuracion'),('auditoria')) m(modulo)
on conflict (rol_clave,modulo) do nothing;

insert into public.metodos_pago_config(nombre,activo,requiere_referencia,orden) values
 ('Efectivo',true,false,1),('Transferencia',true,true,2),('Tarjeta',true,true,3),('Otro',true,false,4)
on conflict (nombre) do nothing;

create or replace view public.v_base_conocimiento_ia as
select 'faq'::text as tipo, id::text as referencia_id, pregunta as titulo, respuesta as contenido,
       categoria, palabras_clave, prioridad, activo, actualizado_en
from public.faq
union all
select 'plantilla', id::text, nombre, contenido, categoria, palabras_clave, 0, activo, actualizado_en
from public.plantillas_respuesta
union all
select 'promocion', id::text, nombre, concat_ws(E'\n',descripcion,condiciones), 'Promociones',
       array['promoción','oferta']::text[], 20, activo, actualizado_en
from public.promociones
where (fecha_inicio is null or fecha_inicio <= current_date) and (fecha_fin is null or fecha_fin >= current_date)
union all
select 'servicio', id::text, nombre,
       concat_ws(E'\n',descripcion, respuesta_cotizacion, recomendaciones, preguntas_frecuentes, instrucciones_agente),
       coalesce(categoria,'Servicios'), coalesce(palabras_clave,'{}'::text[]), 50, activo, coalesce(actualizado_en,now())
from public.catalogo_servicios;

create or replace function public.buscar_conocimiento_ia(termino text, limite integer default 12)
returns table(tipo text, referencia_id text, titulo text, contenido text, categoria text, palabras_clave text[], prioridad integer)
language sql stable security invoker as $$
  select b.tipo,b.referencia_id,b.titulo,b.contenido,b.categoria,b.palabras_clave,b.prioridad
  from public.v_base_conocimiento_ia b
  where b.activo = true and (
    b.titulo ilike '%'||coalesce(termino,'')||'%' or
    b.contenido ilike '%'||coalesce(termino,'')||'%' or
    b.categoria ilike '%'||coalesce(termino,'')||'%' or
    exists(select 1 from unnest(coalesce(b.palabras_clave,'{}'::text[])) p where p ilike '%'||coalesce(termino,'')||'%')
  )
  order by b.prioridad desc, b.titulo
  limit greatest(1,least(coalesce(limite,12),50));
$$;

alter table public.roles_sistema enable row level security;
alter table public.permisos_sistema enable row level security;
alter table public.metodos_pago_config enable row level security;

do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='roles_sistema' and policyname='roles_authenticated') then
  create policy roles_authenticated on public.roles_sistema for all to authenticated using(true) with check(true);
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='permisos_sistema' and policyname='permisos_authenticated') then
  create policy permisos_authenticated on public.permisos_sistema for all to authenticated using(true) with check(true);
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='metodos_pago_config' and policyname='metodos_authenticated') then
  create policy metodos_authenticated on public.metodos_pago_config for all to authenticated using(true) with check(true);
 end if;
end $$;

grant select on public.v_base_conocimiento_ia to authenticated;
grant execute on function public.buscar_conocimiento_ia(text,integer) to authenticated;
