-- TechSoul OS · Sprint 04
-- Inventario, movimientos, proveedores y órdenes de compra.
-- Ejecutar después del Sprint 03.

begin;

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null default 'Refacciones',
  tipo_producto text default '',
  marca text default '',
  compatible_con text default '',
  calidad text default '',
  modalidad text not null default 'stock' check (modalidad in ('stock','bajo_pedido')),
  costo numeric(12,2) not null default 0 check (costo >= 0),
  precio_venta numeric(12,2) not null default 0 check (precio_venta >= 0),
  stock numeric(12,2) not null default 0 check (stock >= 0),
  stock_minimo numeric(12,2) not null default 0 check (stock_minimo >= 0),
  proveedor text default '',
  ubicacion text default '',
  notas text default '',
  activo boolean not null default true,
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint productos_nombre_no_vacio check (length(trim(nombre)) > 0)
);
create index if not exists productos_nombre_idx on public.productos using btree(lower(nombre));
create index if not exists productos_categoria_idx on public.productos(categoria);
create index if not exists productos_stock_idx on public.productos(stock, stock_minimo);

create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.productos(id) on delete set null,
  producto text default '',
  tipo text not null,
  cantidad numeric(12,2) not null default 0 check (cantidad >= 0),
  stock_anterior numeric(12,2) not null default 0,
  stock_nuevo numeric(12,2) not null default 0,
  referencia_tipo text,
  referencia_id text,
  nota text default '',
  motivo text default '',
  fecha_movimiento timestamptz not null default now(),
  usuario_id uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists movimientos_inventario_producto_idx on public.movimientos_inventario(producto_id, fecha_movimiento desc);

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  whatsapp text,
  correo text,
  notas text default '',
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists proveedores_nombre_idx on public.proveedores using btree(lower(nombre));

create table if not exists public.ordenes_compra (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  proveedor_id bigint references public.proveedores(id) on delete set null,
  estado text not null default 'Pendiente',
  metodo_pago text default 'Efectivo',
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  notas text default '',
  fecha_orden timestamptz not null default now(),
  fecha_recepcion timestamptz,
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ordenes_compra_proveedor_idx on public.ordenes_compra(proveedor_id);
create index if not exists ordenes_compra_estado_idx on public.ordenes_compra(estado);

create table if not exists public.ordenes_compra_detalle (
  id bigint generated by default as identity primary key,
  orden_compra_id bigint not null references public.ordenes_compra(id) on delete cascade,
  producto_id bigint references public.productos(id) on delete set null,
  descripcion text not null,
  cantidad numeric(12,2) not null default 1 check (cantidad > 0),
  costo_unitario numeric(12,2) not null default 0 check (costo_unitario >= 0),
  subtotal numeric(12,2) generated always as (cantidad * costo_unitario) stored,
  created_at timestamptz not null default now()
);
create index if not exists oc_detalle_orden_idx on public.ordenes_compra_detalle(orden_compra_id);

create table if not exists public.solicitudes_compra (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.productos(id) on delete set null,
  venta_id bigint,
  detalle_venta_id bigint,
  descripcion text not null,
  cantidad numeric(12,2) not null default 1 check (cantidad > 0),
  proveedor text default '',
  fecha_estimada date,
  cliente_nombre text default '',
  costo_estimado numeric(12,2) not null default 0,
  estado text not null default 'Pendiente',
  notas text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Triggers.
do $$ declare t text; begin
 foreach t in array array['productos','proveedores','ordenes_compra','solicitudes_compra'] loop
  execute format('drop trigger if exists %I on public.%I',t||'_actualizar_updated_at',t);
  execute format('create trigger %I before update on public.%I for each row execute function public.actualizar_updated_at()',t||'_actualizar_updated_at',t);
 end loop;
end $$;

-- RLS.
do $$ declare t text; begin
 foreach t in array array['productos','movimientos_inventario','proveedores','ordenes_compra','ordenes_compra_detalle','solicitudes_compra'] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('drop policy if exists %I on public.%I',t||'_leer',t);
  execute format('create policy %I on public.%I for select to authenticated using (public.mi_rol() is not null)',t||'_leer',t);
  execute format('drop policy if exists %I on public.%I',t||'_insertar',t);
  execute format('create policy %I on public.%I for insert to authenticated with check (public.mi_rol() in (''admin'',''recepcion'',''tecnico''))',t||'_insertar',t);
  execute format('drop policy if exists %I on public.%I',t||'_actualizar',t);
  execute format('create policy %I on public.%I for update to authenticated using (public.mi_rol() in (''admin'',''recepcion'',''tecnico'')) with check (public.mi_rol() in (''admin'',''recepcion'',''tecnico''))',t||'_actualizar',t);
  execute format('drop policy if exists %I on public.%I',t||'_eliminar',t);
  execute format('create policy %I on public.%I for delete to authenticated using (public.es_admin())',t||'_eliminar',t);
  execute format('grant select,insert,update,delete on public.%I to authenticated',t);
 end loop;
end $$;
grant usage, select on all sequences in schema public to authenticated;

commit;
