-- TechSoul AI · Fase 1
create table if not exists public.configuracion_agente_ia (
  id bigint generated by default as identity primary key,
  nombre text not null default 'Soul',
  tono text not null default 'amable_profesional',
  saludo text not null default '¡Hola! Soy Soul, asistente virtual de TechSoul. ¿En qué equipo te ayudo?',
  despedida text not null default 'Con gusto te esperamos en TechSoul.',
  instrucciones text not null default '',
  reglas jsonb not null default '{}'::jsonb,
  activo boolean not null default true,
  actualizado_en timestamptz not null default now()
);

create table if not exists public.conversaciones_ia (
  id bigint generated by default as identity primary key,
  canal text not null default 'simulador',
  cliente_nombre text,
  estado text not null default 'abierta',
  transferida boolean not null default false,
  motivo_transferencia text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.mensajes_ia (
  id bigint generated by default as identity primary key,
  conversacion_id bigint not null references public.conversaciones_ia(id) on delete cascade,
  rol text not null check (rol in ('cliente','agente','sistema')),
  contenido text not null,
  fuentes jsonb not null default '[]'::jsonb,
  confianza numeric(5,2),
  requiere_revision boolean not null default false,
  creado_en timestamptz not null default now()
);

create table if not exists public.respuestas_aprobadas_ia (
  id bigint generated by default as identity primary key,
  pregunta text not null,
  respuesta text not null,
  intencion text,
  palabras_clave text[] not null default '{}',
  origen_mensaje_id bigint references public.mensajes_ia(id) on delete set null,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

insert into public.configuracion_agente_ia (nombre, tono, instrucciones, reglas)
select 'Soul', 'amable_profesional',
  'Responde con claridad, no inventes precios ni diagnósticos y pide el modelo exacto cuando haga falta.',
  '{"no_inventar_precios":true,"no_confirmar_stock_sin_consulta":true,"escalar_humedad":true,"escalar_placa":true,"escalar_cuentas":true}'::jsonb
where not exists (select 1 from public.configuracion_agente_ia);

alter table public.configuracion_agente_ia enable row level security;
alter table public.conversaciones_ia enable row level security;
alter table public.mensajes_ia enable row level security;
alter table public.respuestas_aprobadas_ia enable row level security;

do $$ begin
  create policy "authenticated_config_agente" on public.configuracion_agente_ia for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "authenticated_conversaciones_ia" on public.conversaciones_ia for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "authenticated_mensajes_ia" on public.mensajes_ia for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "authenticated_respuestas_ia" on public.respuestas_aprobadas_ia for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
