-- TechSoul OS - Sprint 2.5
-- Servicios múltiples por orden.

create table if not exists public.orden_servicios (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  tipo_servicio text not null,
  descripcion text not null default '',
  precio numeric(12,2) not null default 0 check (precio >= 0),
  estado text not null default 'Pendiente' check (estado in ('Pendiente','En proceso','Terminado','Entregado')),
  orden_visual integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orden_servicios_orden_id_idx
  on public.orden_servicios(orden_id);

alter table public.orden_servicios enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'orden_servicios'
      and policyname = 'orden_servicios_select_authenticated'
  ) then
    create policy orden_servicios_select_authenticated
      on public.orden_servicios for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'orden_servicios'
      and policyname = 'orden_servicios_insert_authenticated'
  ) then
    create policy orden_servicios_insert_authenticated
      on public.orden_servicios for insert
      to authenticated
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'orden_servicios'
      and policyname = 'orden_servicios_update_authenticated'
  ) then
    create policy orden_servicios_update_authenticated
      on public.orden_servicios for update
      to authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'orden_servicios'
      and policyname = 'orden_servicios_delete_authenticated'
  ) then
    create policy orden_servicios_delete_authenticated
      on public.orden_servicios for delete
      to authenticated
      using (true);
  end if;
end $$;
