-- TechSoul OS · Sprint 03
-- Órdenes, checklist, evidencias, historial, firmas y garantías.
-- Ejecutar después de 202607300002_clientes_equipos.sql.

begin;

create table if not exists public.ordenes (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  cliente_id bigint not null references public.clientes(id) on update cascade on delete restrict,
  equipo_id bigint not null references public.equipos(id) on update cascade on delete restrict,
  presupuesto_id bigint,
  falla_reportada text not null,
  diagnostico text default '',
  trabajo_realizado text default '',
  costo_total numeric(12,2) not null default 0 check (costo_total >= 0),
  anticipo numeric(12,2) not null default 0 check (anticipo >= 0),
  estado text not null default 'Recibido',
  tecnico text default '',
  notas text default '',
  garantia_dias integer not null default 0 check (garantia_dias >= 0),
  garantia_condiciones text default '',
  fecha_ingreso timestamptz not null default now(),
  fecha_entrega timestamptz,
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ordenes_anticipo_valido check (anticipo <= costo_total or costo_total = 0),
  constraint ordenes_falla_no_vacia check (length(trim(falla_reportada)) > 0)
);

create index if not exists ordenes_cliente_idx on public.ordenes(cliente_id);
create index if not exists ordenes_equipo_idx on public.ordenes(equipo_id);
create index if not exists ordenes_estado_idx on public.ordenes(estado);
create index if not exists ordenes_fecha_idx on public.ordenes(fecha_ingreso desc);

create table if not exists public.checklist_orden (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  item text not null,
  estado text not null default 'No probado',
  notas text default '',
  created_at timestamptz not null default now()
);
create index if not exists checklist_orden_idx on public.checklist_orden(orden_id);

create table if not exists public.evidencias (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  tipo text not null default 'Recepción',
  url_imagen text not null,
  descripcion text default '',
  creado_por uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists evidencias_orden_idx on public.evidencias(orden_id);

create table if not exists public.orden_historial (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  tipo text not null default 'actualizacion',
  titulo text not null,
  descripcion text default '',
  estado_anterior text,
  estado_nuevo text,
  usuario_id uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists orden_historial_orden_idx on public.orden_historial(orden_id, created_at desc);

create table if not exists public.firmas_orden (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  tipo text not null default 'Recepción',
  nombre_firmante text,
  firma_base64 text not null,
  created_at timestamptz not null default now()
);
create index if not exists firmas_orden_idx on public.firmas_orden(orden_id);

create table if not exists public.configuracion_garantias (
  id bigint generated by default as identity primary key,
  tipo_servicio text not null unique,
  dias_garantia integer not null default 0 check (dias_garantia >= 0),
  condiciones text default '',
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.garantias (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  tipo_servicio text not null,
  dias_garantia integer not null default 0 check (dias_garantia >= 0),
  fecha_inicio timestamptz not null default now(),
  condiciones text default '',
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists garantias_orden_idx on public.garantias(orden_id);

create table if not exists public.reclamaciones_garantia (
  id bigint generated by default as identity primary key,
  garantia_id bigint not null references public.garantias(id) on delete cascade,
  motivo text not null,
  diagnostico text default '',
  resolucion text default '',
  estado text not null default 'En revisión',
  notas text default '',
  fecha_reclamacion timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists reclamaciones_garantia_idx on public.reclamaciones_garantia(garantia_id);

-- Triggers updated_at.
do $$
declare t text;
begin
  foreach t in array array['ordenes','configuracion_garantias','garantias','reclamaciones_garantia'] loop
    execute format('drop trigger if exists %I on public.%I', t || '_actualizar_updated_at', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.actualizar_updated_at()', t || '_actualizar_updated_at', t);
  end loop;
end $$;

insert into public.configuracion_garantias(tipo_servicio,dias_garantia,condiciones,activo)
values
 ('Pantalla',90,'Garantía en funcionamiento del touch. No cubre golpes, humedad ni mal uso.',true),
 ('Batería alta capacidad',180,'Garantía por defecto de fabricación. No cubre golpes, humedad ni manipulación.',true),
 ('Reparación',30,'Garantía sobre el trabajo realizado.',true)
on conflict (tipo_servicio) do nothing;

-- RLS homogéneo para las tablas del sprint.
do $$
declare t text;
begin
  foreach t in array array['ordenes','checklist_orden','evidencias','orden_historial','firmas_orden','configuracion_garantias','garantias','reclamaciones_garantia'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_leer', t);
    execute format('create policy %I on public.%I for select to authenticated using (public.mi_rol() is not null)', t || '_leer', t);
    execute format('drop policy if exists %I on public.%I', t || '_insertar', t);
    execute format('create policy %I on public.%I for insert to authenticated with check (public.mi_rol() in (''admin'',''recepcion'',''tecnico''))', t || '_insertar', t);
    execute format('drop policy if exists %I on public.%I', t || '_actualizar', t);
    execute format('create policy %I on public.%I for update to authenticated using (public.mi_rol() in (''admin'',''recepcion'',''tecnico'')) with check (public.mi_rol() in (''admin'',''recepcion'',''tecnico''))', t || '_actualizar', t);
    execute format('drop policy if exists %I on public.%I', t || '_eliminar', t);
    execute format('create policy %I on public.%I for delete to authenticated using (public.es_admin())', t || '_eliminar', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;
grant usage, select on all sequences in schema public to authenticated;

-- El frontend actual usa URL directa. Se conserva el bucket de evidencias público
-- para que las imágenes funcionen después de recargar la orden.
insert into storage.buckets(id,name,public)
values ('evidencias','evidencias',true)
on conflict(id) do update set public=true;

commit;
