-- TechSoul OS · Sprint final · Entregas 1–3
-- Base de conocimiento, configuración administrativa, auditoría y vistas analíticas.

create extension if not exists pgcrypto;

create table if not exists public.configuracion_negocio (
  id bigint generated by default as identity primary key,
  nombre_negocio text not null default 'TechSoul',
  telefono text,
  whatsapp text,
  direccion text,
  correo text,
  sitio_web text,
  logo_url text,
  condiciones_generales text,
  fecha_actualizacion timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Compatibilidad con instalaciones anteriores de TechSoul OS.
alter table public.configuracion_negocio add column if not exists nombre_negocio text not null default 'TechSoul';
alter table public.configuracion_negocio add column if not exists razon_social text;
alter table public.configuracion_negocio add column if not exists telefono text;
alter table public.configuracion_negocio add column if not exists whatsapp text;
alter table public.configuracion_negocio add column if not exists correo text;
alter table public.configuracion_negocio add column if not exists direccion text;
alter table public.configuracion_negocio add column if not exists sitio_web text;
alter table public.configuracion_negocio add column if not exists logo_url text;
alter table public.configuracion_negocio add column if not exists condiciones_generales text;
alter table public.configuracion_negocio add column if not exists ubicacion_maps text;
alter table public.configuracion_negocio add column if not exists horario text;
alter table public.configuracion_negocio add column if not exists moneda text not null default 'MXN';
alter table public.configuracion_negocio add column if not exists garantia_default_dias integer not null default 90;
alter table public.configuracion_negocio add column if not exists prefijo_folio text not null default 'TS';
alter table public.configuracion_negocio add column if not exists fecha_actualizacion timestamptz not null default now();
alter table public.configuracion_negocio add column if not exists creado_en timestamptz not null default now();
alter table public.configuracion_negocio add column if not exists actualizado_en timestamptz not null default now();

create table if not exists public.faq (
  id bigint generated by default as identity primary key,
  pregunta text not null,
  respuesta text not null,
  categoria text not null default 'General',
  palabras_clave text[] not null default '{}',
  prioridad integer not null default 0,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.promociones (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text not null default '',
  fecha_inicio date,
  fecha_fin date,
  imagen_url text,
  condiciones text,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint promociones_fechas_validas check (fecha_fin is null or fecha_inicio is null or fecha_fin >= fecha_inicio)
);

create table if not exists public.plantillas_respuesta (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null default 'General',
  contenido text not null,
  palabras_clave text[] not null default '{}',
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.auditoria (
  id bigint generated by default as identity primary key,
  usuario_id uuid,
  usuario_nombre text,
  modulo text not null,
  accion text not null,
  entidad text,
  entidad_id text,
  detalle jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now()
);

alter table if exists public.catalogo_servicios add column if not exists tiempo_estimado_min integer;
alter table if exists public.catalogo_servicios add column if not exists recomendaciones text;
alter table if exists public.catalogo_servicios add column if not exists palabras_clave text[] not null default '{}';
alter table if exists public.catalogo_servicios add column if not exists respuesta_cotizacion text;

create index if not exists faq_activo_categoria_idx on public.faq (activo, categoria);
create index if not exists promociones_vigencia_idx on public.promociones (activo, fecha_inicio, fecha_fin);
create index if not exists plantillas_activo_categoria_idx on public.plantillas_respuesta (activo, categoria);
create index if not exists auditoria_modulo_fecha_idx on public.auditoria (modulo, creado_en desc);

insert into public.configuracion_negocio (nombre_negocio, telefono, whatsapp, direccion, moneda, garantia_default_dias, prefijo_folio)
select 'TechSoul', '6677487373', '6677487373', 'Blvd. Jardín de las Orquídeas 2584-B, Santa Fe, Culiacán, Sin.', 'MXN', 90, 'TS'
where not exists (select 1 from public.configuracion_negocio);

insert into public.faq (pregunta, respuesta, categoria, palabras_clave, prioridad)
select * from (values
  ('¿Dónde están ubicados?', 'Estamos en Blvd. Jardín de las Orquídeas 2584-B, Santa Fe, Culiacán.', 'Ubicación', array['ubicación','dirección','dónde'], 100),
  ('¿Qué diferencia hay entre INCELL y OLED?', 'INCELL es una opción económica y funcional. OLED ofrece mejores negros, contraste y una experiencia más cercana a la pantalla original.', 'Pantallas', array['incell','oled','pantalla'], 90),
  ('¿Qué debo hacer si mi celular se mojó?', 'Apágalo, no lo cargues y tráelo cuanto antes para diagnóstico. Encenderlo o conectarlo puede aumentar el daño.', 'Diagnóstico', array['mojado','agua','humedad'], 95)
) as seed(pregunta,respuesta,categoria,palabras_clave,prioridad)
where not exists (select 1 from public.faq);

insert into public.plantillas_respuesta (nombre, categoria, contenido, palabras_clave)
select * from (values
  ('Cotización pantalla', 'Cotización', 'Claro. Para cotizarte correctamente necesito el modelo exacto de tu equipo y saber si la imagen y el touch todavía funcionan.', array['pantalla','display','cristal']),
  ('Cotización batería', 'Cotización', 'Claro. Compárteme el modelo exacto de tu equipo para revisar las opciones de batería, precio y garantía.', array['batería','pila','salud']),
  ('Equipo mojado', 'Diagnóstico', 'Apágalo y evita conectarlo al cargador. Podemos revisarlo y realizar un diagnóstico para determinar qué componentes fueron afectados.', array['mojado','agua','humedad'])
) as seed(nombre,categoria,contenido,palabras_clave)
where not exists (select 1 from public.plantillas_respuesta);

-- Vista normalizada para reportes. Tolera esquemas donde las fechas estén en columnas diferentes.
create or replace view public.v_reporte_caja as
select
  id,
  coalesce(fecha_movimiento, created_at) as fecha,
  lower(coalesce(tipo,'')) as tipo_normalizado,
  coalesce(monto,0)::numeric as monto,
  concepto,
  metodo_pago,
  referencia_tipo,
  referencia_id
from public.movimientos_caja;

create or replace view public.v_reporte_ordenes as
select
  o.id,
  o.folio,
  coalesce(o.fecha_ingreso, o.created_at) as fecha,
  o.estado,
  coalesce(o.costo_total,0)::numeric as total,
  coalesce(o.anticipo,0)::numeric as anticipo,
  greatest(0, coalesce(o.costo_total,0) - coalesce(o.anticipo,0))::numeric as saldo,
  e.marca,
  e.modelo,
  c.nombre as cliente
from public.ordenes o
left join public.equipos e on e.id = o.equipo_id
left join public.clientes c on c.id = o.cliente_id;

create or replace view public.v_reporte_servicios as
select
  os.tipo_servicio as tipo,
  count(*)::bigint as cantidad,
  sum(coalesce(os.precio,0))::numeric as importe
from public.orden_servicios os
group by os.tipo_servicio;

alter table public.configuracion_negocio enable row level security;
alter table public.faq enable row level security;
alter table public.promociones enable row level security;
alter table public.plantillas_respuesta enable row level security;
alter table public.auditoria enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='configuracion_negocio' and policyname='configuracion_authenticated') then
    create policy configuracion_authenticated on public.configuracion_negocio for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='faq' and policyname='faq_authenticated') then
    create policy faq_authenticated on public.faq for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='promociones' and policyname='promociones_authenticated') then
    create policy promociones_authenticated on public.promociones for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='plantillas_respuesta' and policyname='plantillas_authenticated') then
    create policy plantillas_authenticated on public.plantillas_respuesta for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='auditoria' and policyname='auditoria_authenticated') then
    create policy auditoria_authenticated on public.auditoria for all to authenticated using (true) with check (true);
  end if;
end $$;
